import assert from "node:assert/strict";
import { chromium } from "playwright";
import { collectPageErrors } from "./qa_helpers.mjs";

const baseUrl = process.env.BASE_URL ?? "http://127.0.0.1:3100";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = collectPageErrors(page);
await page.goto(`${baseUrl}/?screen=play&skipBriefing=1`, { waitUntil: "networkidle" });
await page.getByRole("button", { name: "일시정지" }).click();
const before = await page.getByText(/3:\d\d/).first().innerText();
await page.waitForTimeout(1_200);
assert.equal(await page.getByText(before, { exact: true }).isVisible(), true);
await page.getByRole("button", { name: "작전 포기" }).click();
await page.getByText("작전을 종료했습니다").waitFor();
await page.waitForTimeout(1_000);
assert.equal(await page.getByText("작전을 종료했습니다").isVisible(), true);
assert.deepEqual(errors, []);
await browser.close();
console.log("Termination smoke PASSED: pause freezes timers and abandon remains final");
