import assert from "node:assert/strict";
import { chromium } from "playwright";
import { collectPageErrors, fulfillDialogue } from "./qa_helpers.mjs";

const baseUrl = process.env.BASE_URL ?? "http://127.0.0.1:3100";
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errors = collectPageErrors(page);
await page.route("**/api/dialogue", (route) => fulfillDialogue(route, "fallback"));
await page.goto(`${baseUrl}/?screen=play&skipBriefing=1`, { waitUntil: "networkidle" });
await page.locator(".incident-row").filter({ hasText: "빵집 화재" }).click();
await page.locator(".robot-card").filter({ hasText: "BUDDY" }).click();
await page.getByRole("button", { name: /^주민 대피/ }).click();
await page.getByText("LOCAL SAFE").waitFor();
await page.getByRole("button", { name: "가스통 위치를 FIX에 공유" }).click();
await page.waitForFunction(() => window.__PIXEL_PANIC_DEBUG__?.game?.robots?.buddy?.status !== "idle");
assert.equal(await page.locator("input, textarea").count(), 0);
assert.deepEqual(errors, []);
await browser.close();
console.log("Dialogue fallback PASSED: no natural-language input, LOCAL SAFE choice keeps game running");
